import { Inter } from 'next/font/google'
import './globals.css'
import 'react-perfect-scrollbar/dist/css/styles.css';
import Sidebar from '@/components/layout/Sidebar'
import Header from '@/components/layout/Header/Header';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'maGuy dashboard App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + 'box-border min-h-full'}>
        <div className='flex h-screen'>
          <Sidebar />
          <div className='grow'>
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
